name: android

jobs:
  build:
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: flutter_application/pubspec.yaml
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle