name: android

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: flutter_application/pubspec.yaml
      - run: cd flutter_application
      - run: cd flutter_application && flutter pub get
      - run: cd flutter_application && flutter test
      - run: cd flutter_application && flutter build apk
      - run: cd flutter_application && flutter build appbundle